In [3]:
# EXERCICE 1: Création et manipulation de tableaux NumPy
import numpy as np
lst =  [5, 10, 15, 20, 25]
v = np.array(lst, dtype=np.int32)
v

array([ 5, 10, 15, 20, 25])

In [5]:
import numpy as np
lst =  [5, 10, 15, 20, 25]
v = np.array(lst, dtype=np.float64)
v

array([ 5., 10., 15., 20., 25.])

In [7]:
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
M = np.array(list_of_lists)

M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
M = np.array(list_of_lists)
print(M.shape)
M.size

(3, 3)


9

In [17]:
gaussian = np.random.randn(2 * 3 * 4)
gaussian = gaussian.reshape(2, 3, 4)
gaussian

array([[[-0.40294901,  0.60046509, -0.28267856, -1.0537688 ],
        [ 0.36744159, -0.44210557,  1.34930243, -0.38990247],
        [-0.44101674,  0.51848251,  1.20582843, -0.70626291]],

       [[ 1.04295365,  0.82179999,  0.35688075,  0.85629142],
        [ 0.71906439,  1.80910843,  0.61771104, -0.01382897],
        [-0.50034274,  0.69811362,  0.91605323,  0.91005531]]])

In [3]:
# EXERCICE 2: Manipulations avancées des tableaux
lst =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
v = np.array(lst, dtype=np.int64)
v


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [5]:
# 1. Inversion d'un tableau 1D
np.flip(v)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

In [55]:
import numpy as np

# Créer un tableau NumPy 2D avec les nombres de 0 à 11, en forme de 3x4
array = np.arange(12).reshape(3, 4)
array


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
# 2. Extraction d'un sous-tableau spécifique
arr5 = np.arange(12).reshape(3, 4)[:2, -2:]
print("Sous-tableau:", arr5)

Sous-tableau: [[2 3]
 [6 7]]


In [61]:
#3. Créer un tableau 5x5 avec des entiers aléatoires entre 0 et 10
array = np.random.randint(0, 11, (5, 5))

array

array([[10,  1,  0,  0,  0],
       [ 6,  4,  7, 10,  7],
       [ 9,  1,  1,  5,  1],
       [ 5,  7,  3,  3,  7],
       [ 6,  3,  1,  3,  5]])

In [63]:
# Remplacer tous les éléments > 5 par 0
array[array > 5] = 0

# Afficher le tableau modifié
print(array)

[[0 1 0 0 0]
 [0 4 0 0 0]
 [0 1 1 5 1]
 [5 0 3 3 0]
 [0 3 1 3 5]]


In [9]:
# EXERCICE 3: Initialisation et attributs
# 1. Création d'une matrice identité
identity_matrix = np.eye(3)
print("Matrice identité:", identity_matrix)

# 2. Génération d'un tableau linéairement espacé
linspace_arr = np.linspace(0, 5, 10)
print("Linspace:", linspace_arr)

# 3. Création d'un tableau 3D aléatoire et calcul de la somme
random_3D = np.random.randn(2, 3, 4)
print("Somme des éléments:", np.sum(random_3D))

Matrice identité: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Linspace: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Somme des éléments: 5.176380859148075


In [11]:
# EXERCICE 4: Indexation avancée et masquage
# 1. Sélection d'éléments spécifiques
arr7 = np.random.randint(0, 50, 20)
print("Éléments sélectionnés:", arr7[[2, 5, 7, 10, 15]])

# 2. Filtrage avec un masque booléen
arr8 = np.random.randint(0, 30, (4, 5))
print("Masquage > 15:", arr8[arr8 > 15])

# 3. Remplacement des valeurs négatives par 0
arr9 = np.random.randint(-10, 10, 10)
arr9[arr9 < 0] = 0
print("Valeurs négatives remplacées:", arr9)

Éléments sélectionnés: [45 37 13 10  9]
Masquage > 15: [22 21 26 25 29 28 18]
Valeurs négatives remplacées: [0 0 0 0 0 3 0 4 0 0]


In [13]:
# EXERCICE 5: Combinaison et division
# 1. Concatenation de tableaux 1D
arr10 = np.concatenate((np.random.randint(0, 10, 5), np.random.randint(0, 10, 5)))
print("Concaténation:", arr10)

# 2. Division d'un tableau 2D en lignes
arr11 = np.random.randint(0, 10, (6, 4))
split_rows = np.split(arr11, 2, axis=0)
print("Split par lignes:", split_rows)

# 3. Division en colonnes
arr12 = np.random.randint(0, 10, (3, 6))
split_cols = np.split(arr12, 3, axis=1)
print("Split par colonnes:", split_cols)

Concaténation: [8 4 7 8 8 9 9 1 0 2]
Split par lignes: [array([[1, 1, 3, 8],
       [9, 7, 4, 7],
       [9, 6, 0, 8]]), array([[8, 9, 3, 1],
       [0, 7, 7, 9],
       [3, 6, 6, 1]])]
Split par colonnes: [array([[2, 3],
       [4, 9],
       [9, 2]]), array([[5, 0],
       [5, 9],
       [5, 4]]), array([[5, 7],
       [6, 6],
       [8, 8]])]


In [15]:
# EXERCICE 6: Fonctions mathématiques
# 1. Calcul de statistiques sur un tableau
arr13 = np.random.randint(1, 100, 15)
print("Moyenne:", np.mean(arr13), "Médiane:", np.median(arr13), "Écart-type:", np.std(arr13), "Variance:", np.var(arr13))

# 2. Somme des lignes et colonnes
arr14 = np.random.randint(1, 50, (4, 4))
print("Somme des lignes:", np.sum(arr14, axis=1), "Somme des colonnes:", np.sum(arr14, axis=0))

# 3. Min et max sur un tableau 3D
arr15 = np.random.randint(1, 20, (2, 3, 4))
print("Max par axe:", np.max(arr15, axis=1), "Min par axe:", np.min(arr15, axis=2))

Moyenne: 40.86666666666667 Médiane: 39.0 Écart-type: 30.028578979957665 Variance: 901.7155555555554
Somme des lignes: [123 118  65  51] Somme des colonnes: [ 90 118  67  82]
Max par axe: [[16 11 17 12]
 [14 17  6 16]] Min par axe: [[6 6 1]
 [2 6 1]]


In [17]:
# EXERCICE 7: Reshape et transposition
# 1. Transformation d'un tableau 1D en 2D
arr16 = np.arange(1, 13).reshape(3, 4)
print("Tableau reshaped:", arr16)

# 2. Transposition d'un tableau
arr17 = np.random.randint(1, 10, (3, 4)).T
print("Tableau transposé:", arr17)

# 3. Aplatissement d'un tableau
arr18 = np.random.randint(1, 10, (2, 3)).flatten()
print("Tableau aplati:", arr18)


Tableau reshaped: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Tableau transposé: [[9 4 7]
 [1 1 2]
 [8 2 6]
 [8 3 9]]
Tableau aplati: [5 5 3 1 6 7]


In [19]:
# EXERCICE 8: Broadcasting et opérations vectorisées
# 1. Normalisation d'un tableau par colonne
arr19 = np.random.randint(1, 10, (3, 4))
normalized = arr19 - np.mean(arr19, axis=0)
print("Normalisé:", normalized)

# 2. Produit extérieur
arr20 = np.random.randint(1, 5, 4)
print("Produit extérieur:", np.outer(arr20, arr20))

# 3. Augmentation conditionnelle d'un tableau
arr21 = np.random.randint(1, 10, (4, 5))
arr21[arr21 > 5] += 10
print("Tableau modifié:", arr21)

Normalisé: [[-2.66666667 -1.33333333  1.33333333 -1.66666667]
 [ 0.33333333  0.66666667 -0.66666667  3.33333333]
 [ 2.33333333  0.66666667 -0.66666667 -1.66666667]]
Produit extérieur: [[ 9  6 12  9]
 [ 6  4  8  6]
 [12  8 16 12]
 [ 9  6 12  9]]
Tableau modifié: [[ 2  3  5  5  3]
 [ 2 16  5 17 18]
 [17  5  2  5 18]
 [18 18  3  5  1]]


In [21]:
# EXERCICE 9: Tri et recherche
# 1. Tri d'un tableau 1D
arr22 = np.sort(np.random.randint(1, 20, 10))
print("Trié:", arr22)

# 2. Tri d'un tableau 2D par colonne
arr23 = np.random.randint(1, 50, (3, 5))
sorted_arr = arr23[arr23[:, 1].argsort()]
print("Trié par colonne:", sorted_arr)

# 3. Recherche d'indices d'éléments spécifiques
indices = np.where(np.random.randint(1, 100, 15) > 50)
print("Indices des éléments > 50:", indices)

Trié: [ 3  4  4  8  9 11 12 12 15 16]
Trié par colonne: [[34 29 14  5 42]
 [40 33 17 48  5]
 [16 49 15 17 26]]
Indices des éléments > 50: (array([ 1,  2,  4, 11, 13], dtype=int64),)


In [23]:
# EXERCICE 10: Algèbre linéaire
# 1. Création d'une matrice et calcul du déterminant
mat1 = np.random.randint(1, 10, (2, 2))
determinant = np.linalg.det(mat1)
print("Matrice:", mat1)
print("Déterminant:", determinant)

# 2. Calcul des valeurs propres et vecteurs propres
mat2 = np.random.randint(1, 5, (3, 3))
eigvals, eigvecs = np.linalg.eig(mat2)
print("Matrice:", mat2)
print("Valeurs propres:", eigvals)
print("Vecteurs propres:", eigvecs)

# 3. Multiplication matricielle
mat3 = np.random.randint(1, 10, (2, 3))
mat4 = np.random.randint(1, 10, (3, 2))
mat_product = np.dot(mat3, mat4)
print("Produit matriciel:", mat_product)

Matrice: [[4 1]
 [7 3]]
Déterminant: 4.999999999999998
Matrice: [[4 1 2]
 [4 4 4]
 [3 1 3]]
Valeurs propres: [8. 2. 1.]
Vecteurs propres: [[-0.40824829 -0.23570226 -0.2981424 ]
 [-0.81649658  0.94280904 -0.59628479]
 [-0.40824829 -0.23570226  0.74535599]]
Produit matriciel: [[ 14  70]
 [ 15 111]]


In [25]:
# EXERCICE 11: Échantillonnage et distributions
# 1. Génération d'un échantillon uniforme
uniform_samples = np.random.rand(10)
print("Échantillon uniforme:", uniform_samples)

# 2. Génération d'un échantillon normal
normal_samples = np.random.randn(3, 3)
print("Échantillon normal:", normal_samples)

# 3. Création d'un histogramme
histogram_data = np.random.randint(1, 100, 20)
histogram = np.histogram(histogram_data, bins=5)
print("Histogramme:", histogram)


Échantillon uniforme: [0.44920346 0.62454018 0.37480697 0.23490329 0.59113816 0.44668056
 0.61903796 0.27014867 0.94881981 0.3301266 ]
Échantillon normal: [[ 0.44675831 -0.5419971   1.50496659]
 [ 0.63347674 -1.48397092  0.04332252]
 [ 0.74054246 -1.22745729 -0.41128307]]
Histogramme: (array([4, 5, 7, 1, 3], dtype=int64), array([ 2. , 18.8, 35.6, 52.4, 69.2, 86. ]))


In [27]:
# EXERCICE 12: Indexation avancée
# 1. Sélection des éléments diagonaux
arr24 = np.random.randint(1, 20, (5, 5))
diagonal = np.diag(arr24)
print("Éléments diagonaux:", diagonal)

# 2. Sélection des nombres premiers
arr25 = np.random.randint(1, 50, 10)
is_prime = lambda x: all(x % i != 0 for i in range(2, int(x**0.5) + 1)) and x > 1
prime_numbers = arr25[[is_prime(i) for i in arr25]]
print("Nombres premiers:", prime_numbers)

# 3. Sélection des nombres pairs
even_numbers = arr25[arr25 % 2 == 0]
print("Nombres pairs:", even_numbers)

Éléments diagonaux: [13  7  4 14  2]
Nombres premiers: [43]
Nombres pairs: [46 18 10 30  8 48]


In [29]:
# EXERCICE 13: Gestion des valeurs manquantes
# 1. Création d'un tableau avec des NaN
arr26 = np.random.randint(1, 10, 10).astype(float)
arr26[np.random.choice(10, 3, replace=False)] = np.nan
print("Tableau avec NaN:", arr26)

# 2. Remplacement des NaN par la moyenne
arr26[np.isnan(arr26)] = np.nanmean(arr26)
print("Tableau avec NaN remplacés:", arr26)

# 3. Identification des indices contenant des NaN
nan_indices = np.where(np.isnan(arr26))
print("Indices des NaN:", nan_indices)

Tableau avec NaN: [ 3. nan  9.  4.  4. nan  2.  5. nan  2.]
Tableau avec NaN remplacés: [3.         4.14285714 9.         4.         4.         4.14285714
 2.         5.         4.14285714 2.        ]
Indices des NaN: (array([], dtype=int64),)


In [31]:
# EXERCICE 14: Optimisation
# 1. Création d'un grand tableau et calcul optimisé de la moyenne
arr28 = np.random.randint(1, 100, 1_000_000)
avg = np.mean(arr28)
print("Moyenne calculée efficacement:", avg)

# 2. Addition de grandes matrices
arr29 = np.random.randint(1, 10, (1000, 1000))
arr30 = np.random.randint(1, 10, (1000, 1000))
large_sum = arr29 + arr30
print("Addition rapide de grandes matrices:", large_sum)

# 3. Somme selon différents axes
arr31 = np.random.randint(1, 10, (100, 100, 100))
sum_axes = np.sum(arr31, axis=0)
print("Somme sur un axe spécifique:", sum_axes)

Moyenne calculée efficacement: 50.001537
Addition rapide de grandes matrices: [[ 8 11  5 ...  7 10 10]
 [11  7 18 ... 11 10  8]
 [13 11  7 ...  6  6  7]
 ...
 [10 17  2 ... 10 18  8]
 [ 9 10  3 ... 14  8  6]
 [18 15  4 ... 11 13 11]]
Somme sur un axe spécifique: [[519 452 492 ... 498 491 511]
 [482 478 554 ... 510 518 512]
 [481 505 475 ... 505 493 486]
 ...
 [475 502 528 ... 451 492 501]
 [506 453 515 ... 508 468 460]
 [486 482 534 ... 533 501 507]]


In [33]:
# EXERCICE 15: Fonctions cumulatives
# 1. Somme cumulative
arr32 = np.arange(1, 11)
cumsum_values = np.cumsum(arr32)
print("Somme cumulative:", cumsum_values)

# 2. Produit cumulatif
cumprod_values = np.cumprod(arr32)
print("Produit cumulatif:", cumprod_values)

# 3. Cumulatif par lignes et colonnes
arr33 = np.random.randint(1, 20, (4, 4))
cumsum_rows = np.cumsum(arr33, axis=1)
cumsum_cols = np.cumsum(arr33, axis=0)
print("Cumulatif par lignes:", cumsum_rows)
print("Cumulatif par colonnes:", cumsum_cols)

Somme cumulative: [ 1  3  6 10 15 21 28 36 45 55]
Produit cumulatif: [      1       2       6      24     120     720    5040   40320  362880
 3628800]
Cumulatif par lignes: [[12 24 37 45]
 [ 6 13 26 29]
 [15 18 34 44]
 [17 19 30 33]]
Cumulatif par colonnes: [[12 12 13  8]
 [18 19 26 11]
 [33 22 42 21]
 [50 24 53 24]]


In [35]:
# EXERCICE 16: Dates et temps
# 1. Génération d'une plage de dates journalières
date_range = np.arange('2023-02-01', '2023-02-11', dtype='datetime64[D]')
print("Dates journalières:", date_range)

# 2. Génération d'une plage de dates mensuelles
month_range = np.arange('2022-01', '2022-06', dtype='datetime64[M]')
print("Dates mensuelles:", month_range)

# 3. Conversion de timestamps en datetime
timestamps = np.random.randint(1672531200, 1704067200, 10)
datetime_arr = np.datetime64(0, 's') + timestamps
print("Timestamps convertis:", datetime_arr)

Dates journalières: ['2023-02-01' '2023-02-02' '2023-02-03' '2023-02-04' '2023-02-05'
 '2023-02-06' '2023-02-07' '2023-02-08' '2023-02-09' '2023-02-10']
Dates mensuelles: ['2022-01' '2022-02' '2022-03' '2022-04' '2022-05']
Timestamps convertis: ['2023-03-14T14:59:53' '2023-10-23T04:03:34' '2023-01-17T20:09:30'
 '2023-07-01T07:29:45' '2023-04-28T01:07:24' '2023-04-27T06:04:10'
 '2023-05-09T07:25:11' '2023-03-08T07:34:19' '2023-04-17T06:25:41'
 '2023-09-04T03:01:15']


In [37]:
# EXERCICE 17: Types personnalisés
# 1. Création d'un tableau structuré pour stocker des informations sur des livres
structured_dtype = np.dtype([('title', 'S50'), ('author', 'S50'), ('pages', np.int32)])
books = np.array([
    (b"Python Basics", b"John Doe", 300),
    (b"Advanced NumPy", b"Jane Smith", 450),
    (b"Machine Learning", b"Alice Brown", 500)
], dtype=structured_dtype)
print("Livres en tableau structuré:", books)

# 2. Création d'un tableau avec entiers et leur représentation binaire
binary_dtype = np.dtype([('number', np.int32), ('binary', 'S10')])
binary_arr = np.array([(i, bin(i)[2:].encode()) for i in range(5)], dtype=binary_dtype)
print("Représentation binaire:", binary_arr)

# 3. Création d'un tableau avec nombres complexes
complex_dtype = np.dtype([('real', np.float64), ('imag', np.float64)])
complex_arr = np.array([(1, 2), (3, 4), (5, 6)], dtype=complex_dtype)
print("Tableau de nombres complexes:", complex_arr)

Livres en tableau structuré: [(b'Python Basics', b'John Doe', 300)
 (b'Advanced NumPy', b'Jane Smith', 450)
 (b'Machine Learning', b'Alice Brown', 500)]
Représentation binaire: [(0, b'0') (1, b'1') (2, b'10') (3, b'11') (4, b'100')]
Tableau de nombres complexes: [(1., 2.) (3., 4.) (5., 6.)]
